version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_RUN_HOST=0.0.0.0
      - FRONTEND_ORIGIN=http://${APP_HOST}:5173
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./server:/app
    command: sh -c "sleep 10 && python run.py"

  frontend:
    build: 
      context: ./client
      args:
        - VITE_API_BASE_URL=http://${APP_HOST}:5001
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://${APP_HOST}:5001 
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s



volumes:
  postgres_data:

