version: "3.8"

services:

  backend:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://zeller:june1200@db:5432/stock_analyzer_database
      - REDIS_URL=redis://redis:6379/0
      - FLASK_APP=app
      - FLASK_ENV=development
      - SECRET_KEY=1qaz2wsx3edc4rfv5tgb6yhn7ujm8ik9ol0p
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: sh -c "sleep 10 && flask run --host=0.0.0.0"

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=stock_analyzer_database
      - POSTGRES_USER=zeller
      - POSTGRES_PASSWORD=june1200
    volumes:
      - postgres_data:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zeller -d stock_analyzer_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:6-alpine
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
  redis_data:
