"""Recreate database structure

Revision ID: 88384e70f080
Revises: 
Create Date: 2024-11-30 14:06:32.814157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88384e70f080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_master_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_stock_symbol')
        batch_op.create_foreign_key(None, 'stock_master', ['stock_master_id'], ['id'])
        batch_op.drop_column('hold_rating')
        batch_op.drop_column('dividend_yield')
        batch_op.drop_column('pe_ratio')
        batch_op.drop_column('price')
        batch_op.drop_column('industry')
        batch_op.drop_column('ev_to_ebita')
        batch_op.drop_column('symbol')
        batch_op.drop_column('name')
        batch_op.drop_column('sell_rating')
        batch_op.drop_column('buy_rating')
        batch_op.drop_column('market_cap')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('buy_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sell_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ev_to_ebita', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dividend_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hold_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_stock_symbol', ['symbol'], unique=True)
        batch_op.drop_column('stock_master_id')

    # ### end Alembic commands ###
