"""add tier and alphabot usage to user

Revision ID: d31b24c81152
Revises: 3252ba729ffc
Create Date: 2026-06-22 02:26:46.330825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31b24c81152'
down_revision = '3252ba729ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('alphabot_daily_uses', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('alphabot_last_use_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alphabot_last_use_date')
        batch_op.drop_column('alphabot_daily_uses')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
